### ISSUE TITLE
request description of data and clock pins specifying both GP# and pad#  

### ISSUE THREAD

**Issue by TPMoyer** [endail/hx711-pico-c#19]
Current main.c,  calibration.c and test.c have
   // SET THESE TO THE GPIO PINS CONNECTED TO THE
    // HX711's CLOCK AND DATA PINS
    const uint clkPin = 14;
    const uint datPin = 15;
request
    const uint clkPin = 14;  /* GP14  pad 19 */
    const uint datPin = 15;  /* GP15 pad 20 */

This might help someone else to avoid making the same mistake I did: connecting to pads 14 and 15.

You can make something foolproof
but you can't make it damn foolproof
because some damn fool will still find a way...

**Comment by endail** [comment]
Thanks.

I've updated the documentation to those files and the readme.

**Comment by TPMoyer** [comment]
Thanks.   I felt kind of stupid when I figured out what I did.
OF COURSE the methods which select the pins use the GP not the pads#...
but have programmed for 40 years with the precept:
   If I messed it up, someone else might too.

Thank you for responding positively.
