### ISSUE TITLE
Unused parameters?

### ISSUE THREAD

**Issue by eugnio1** [endail/hx711-pico-c#57]
<img width="1280" alt="Screenshot 2023-04-27 at 8 57 01 PM" src="https://user-images.githubusercontent.com/125184176/234869889-e5e7e455-4704-4341-9c9d-0813608af091.png">
Any solutions?

**Comment by endail** [comment]
Thanks for letting me know. I should have this fixed for you later today.

**Comment by endail** [comment]
This should be fixed now.

Let me know if it's all OK.
